using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class Item : MonoBehaviour
{
    public ItemData data;
    public int level;
    public Weapon weapon;
    public Gear gear;

    Image icon;
    Text textLevel;
    Text textName;
    Text textDesc;

    void Awake()
    {
        icon = GetComponentsInChildren<Image>()[1];
        icon.sprite = data.itemIcon;

        Text[] texts = GetComponentsInChildren<Text>();
        textLevel = texts[0];
        textName = texts[1];
        textDesc = texts[2];
        textName.text = data.itemName;
    }

    void OnEnable()
    {
        textLevel.text = "Lv." + (level + 1);

        switch (data.itemType)
        {
            case ItemData.ItemType.MeLee:
            case ItemData.ItemType.Range:
            case ItemData.ItemType.Shotgun:
            case ItemData.ItemType.Circle:
            case ItemData.ItemType.Volt:
            case ItemData.ItemType.Rain:
            case ItemData.ItemType.FireWalk:
            case ItemData.ItemType.Black:
            case ItemData.ItemType.BlackHole:
            case ItemData.ItemType.Basic:
            case ItemData.ItemType.test:
            case ItemData.ItemType.test2:
                textDesc.text = string.Format(data.itemDesc,data.damages[level]*100, data.count[level]);
                break;
            case ItemData.ItemType.Glove:
            case ItemData.ItemType.Shoe:
                textDesc.text = string.Format(data.itemDesc, data.damages[level]*100);
                break;
            default:
                textDesc.text = string.Format(data.itemDesc);
                break;

        }
    }
   
    public void onclick()
    {
        switch(data.itemType)
        {
            case ItemData.ItemType.MeLee:
            case ItemData.ItemType.Range:
            case ItemData.ItemType.Shotgun:
            case ItemData.ItemType.Circle:
            case ItemData.ItemType.Volt:
            case ItemData.ItemType.FireWalk:
            case ItemData.ItemType.Rain:
            case ItemData.ItemType.Black:
            case ItemData.ItemType.BlackHole:
            case ItemData.ItemType.Basic:
            case ItemData.ItemType.test:
            case ItemData.ItemType.test2:
                if (level == 0)
                {
                    GameObject newWeapon = new GameObject();
                    weapon = newWeapon.AddComponent<Weapon>();
                    weapon.Init(data);
                }
                else
                {
                    float nextDamage = data.baseDamage;
                    int nextCount = 0;

                    nextDamage += data.baseDamage * data.damages[level];
                    nextCount += data.count[level];

                    weapon.LevelUp(nextDamage, nextCount);
                }
                level++;
                break;
            case ItemData.ItemType.Glove:
            case ItemData.ItemType.Shoe:
                if (level == 0)
                {
                    GameObject newGear = new GameObject();
                    gear = newGear.AddComponent<Gear>();
                    gear.Init(data);
                }
                else
                {
                    float nextRate = data.damages[level];
                    gear.LevelUp(nextRate);
                }
                level++;
                break;
            case ItemData.ItemType.Heal:
                GameManager.instance.health = GameManager.instance.maxHealth;
                break;
        }

        if(level == data.damages.Length)
        {
            GetComponent<Button>().interactable = false;
        }
    }

}
